// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnoZ77e57bNMhNYxdkQIgszTyRyDfp1HU',
    appId: '1:1025171489135:web:a451c244da3923e3fd689a',
    messagingSenderId: '1025171489135',
    projectId: 'payflow-abc82',
    authDomain: 'payflow-abc82.firebaseapp.com',
    storageBucket: 'payflow-abc82.appspot.com',
    measurementId: 'G-DKV9VZ1ZD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRCG-bYYHX6sv3Yt1b38JdQ380HBTIntY',
    appId: '1:1025171489135:android:0aaeead1e224e0a2fd689a',
    messagingSenderId: '1025171489135',
    projectId: 'payflow-abc82',
    storageBucket: 'payflow-abc82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAG01s2RWpZQ95E5BwlHWDNR5FHm_3BhI',
    appId: '1:1025171489135:ios:e9ed829cc9473e6dfd689a',
    messagingSenderId: '1025171489135',
    projectId: 'payflow-abc82',
    storageBucket: 'payflow-abc82.appspot.com',
    iosBundleId: 'com.example.payflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAG01s2RWpZQ95E5BwlHWDNR5FHm_3BhI',
    appId: '1:1025171489135:ios:41a2e8c3e10f6363fd689a',
    messagingSenderId: '1025171489135',
    projectId: 'payflow-abc82',
    storageBucket: 'payflow-abc82.appspot.com',
    iosBundleId: 'com.example.payflow.RunnerTests',
  );
}
